### ISSUE TITLE
Package ‘magree’ is not available (for R version 3.3.2)

### ISSUE THREAD

**Issue by areuneker** [mclements/magree#1]
When trying to import the package from R-Studio on Mac OS 10.12, R prints the following.

package 'magree' is not available (for R version 3.3.2)

I have tried using different mirrors, but that didn't help. Could you tell me whether the package is indeed outdated or whether I did something wrong? I'd really like to use the package, as I'm looking into the identification of problematic subjects in a classification study.

**Comment by mclements** [comment]
Alex,

This package was not on CRAN, but I have now submitted it to CRAN.

If you want to use the package before it is accepted onto CRAN, you can install from GitHub:

require(devtools)
install_github("mclements/magree")

I hope this helps.

Sincerely, Mark.

On 12/08/2016 04:02 PM, Alex Reuneker wrote:

When trying to import the package from R-Studio on Mac OS 10.12, R prints the following.

package 'magree' is not available (for R version 3.3.2)

I have tried using different mirrors, but that didn't help. Could you tell me whether the package is indeed outdated or whether I did something wrong? I'd really like to use the package, as I'm looking into the identification of problematic subjects in a classification study.

**Comment by areuneker** [comment]
Hi Mark,

Thanks for your reply. The problem seemed to be that I didn't have Xcode and gfortran installed, so the package couldn't be compiled. After installing Xcode and gfortran I'm able to use the package.

Thanks again,
Alex
